project:
  type: website

website:
  title: Detecting Fake News with TF-IDF and Machine Learning
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-523-SU25/final-project-lohiya # Need to change to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
